name: Deploy React Application
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  APP_NAME: 'crypto-trading-platform-5' 
  DIST_FOLDER: 'dist'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Build
        run: |
          npm ci
          npm run build
          
          APP_NAME_LOWER=$(echo ${{ env.APP_NAME }} | tr '[:upper:]' '[:lower:]')
          DEPLOY_PATH="/www/wwwroot/${APP_NAME_LOWER}.crm-system.com"
          echo "DEPLOY_PATH=${DEPLOY_PATH}" >> $GITHUB_ENV
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy
        run: | 
            rsync -avz --delete \
            --exclude='.user.ini' \
            --exclude='*.log' \
            --exclude='.htaccess' \
            ${{ env.DIST_FOLDER }}/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ env.DEPLOY_PATH }}/
    
            # Set permissions only on application files (exclude system files)
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            find '${{ env.DEPLOY_PATH }}' -name '.user.ini' -prune -o -type f -exec sudo chown www:www {} + 2>/dev/null || true
            find '${{ env.DEPLOY_PATH }}' -name '.user.ini' -prune -o -type d -exec sudo chown www:www {} + 2>/dev/null || true
            find '${{ env.DEPLOY_PATH }}' -name '.user.ini' -prune -o -type f -exec sudo chmod 644 {} + 2>/dev/null || true
            find '${{ env.DEPLOY_PATH }}' -name '.user.ini' -prune -o -type d -exec sudo chmod 755 {} + 2>/dev/null || true
            "
          
      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh
